
var ID_APPLICATION_PROGRESS_BAR_MODAL_WINDOW = '#dastProxyProgessModal';
var ID_APPLICATION_PROGRESS_BAR = '#dastProxyProgessModalProgessBar';
var ID_APPLICATION_PROGRESS_BAR_MODAL_WINDOW_TITLE = '#dastProxyProgessModalTital';
var LOGGED_IN_USER_WELCOME_BANNER = '#loggedInUserSpan';
var ID_APPLICATION_SUBMIT_RECORDING_OPTIONS_MODAL_WINDOW = '#fileTypeDialog';

// Notification IDs
var ID_APPLICATION_RECORDING_STARTED_NOTIFICATION_DIALOG = '#recordStartedDialog';
var ID_APPLICATION_RECORDING_IN_PROGRESS_NOTIFICATION_DIALOG = '#recordInProgressDialog';
var ID_APPLICATION_SCAN_SET_UP_SUCCESSFUL_NOTIFICATION_DIALOG = '#recordingSubmittedToDASTToolDialog';
var ID_APPLICATION_HTD_CREATION_SUCCESSFUL_NOTIFICATION_DIALOG = '#htdCreationSuccessfulDialog';
var ID_APPLICATION_ERROR_OCCURRED_NOTIFICATION_DIALOG = "#errorInPageDialog";
var ID_APPLICATION_CONTACT_US_SUCCESSFUL_NOTIFICATION_DIALOG = "#contactUsSuccessfulDialog";

// Form Ids
var ID_APPLICATION_CONTACT_US_DIALOG = '#contactTeamDialog';
var ID_APPLICATION_HELP_DIALOG = '#helpDialog';

var START_RECORDING_ELEMENTS = '#startRecordingSpan';
var STOP_RECORDING_ELEMENTS =  '#stopRecordingSpan';

var ID_PROXY_HOST_DETAILS = '#proxyHost';
var ID_PROXY_PORT_DETAILS = '#proxyPort';

//GLOBAL CONSTANTS
var DIALOG_BOX_VISIBLE_TIME_MILLISECONDS = 6000;

var ID_RECORD_SCAN_TAB = '#recordedScanTab';

var ID_SET_UP_SCAN_ON_APPSCAN = '#stopRecordingCarousalOption1';
var ID_GET_RECORDING_AS_HTD = '#stopRecordingCarousalOption2';

var ID_SET_UP_NEW_SPIDER_SCAN_ACTION = '#startNewSpideringScan';

var ID_CONTACT_US_SUBMIT_ACTION = '#submitContactUs';
var ID_CONTACT_US_ISSUE_TYPE_DROP_DOWN = '#contactUsReason';
var ID_CONTACT_US_ISSUE_DESC = '#contactUsReasonDesc';
var ID_SUBMIT_TO_JIRA_MODAL_WINDOW = '#dastProxySubmitToJiraModal';
var ID_SUBMIT_TO_JIRA_SUCCESSFUL_NOTIFICATION_DIALOG = '#issueSubmittedSeccussfullyToJira';
